DROP DATABASE IF EXISTS trippin;
CREATE DATABASE trippin;

\c trippin;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS picturs;




